name = "image-to-pdf-worker"
type = "javascript"
compatibility_date = "2024-01-01"
main = "index.js"

[build]
command = "npm install && npm run build"
upload.format = "service-worker"

[vars]
MAX_IMAGES = "50"
MAX_FILE_SIZE = "8388608" # 8MB in bytes
MAX_TOTAL_SIZE = "104857600" # 110MB in bytes
MEMORY_THRESHOLD = "115343360" # 50MB in bytes

[limits]
cpu_ms = 30000  # 30秒CPU时间
memory = 128    # 128MB内存限制
